[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  VITE_SUPABASE_URL = "https://adgdwehuxdddcwmfhudx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ2R3ZWh1eGRkZGN3bWZodWR4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxODY0NjkyMywiZXhwIjoyMDM0MjIyOTIzfQ.0nnPWXFwHWnMw3ddSNo3e6uJVx-FS3L3wcunSObYLL0"
